#!/usr/bin/env python3
"""
Aggregate RSS/Atom feeds listed in a file and serve a combined RSS feed.

Usage:
  /opt/homebrew/bin/python3 rss_aggregator.py --feeds-file rss_feeds.txt --host 127.0.0.1 --port 8090

Endpoints:
  / or /feed or /feed.xml   Combined RSS output
  /health                   JSON status and last refresh metadata

Notes:
    - Source list file format: one URL per line; blank lines and lines starting
        with # are ignored.
    - Source URLs can be RSS, Atom, sitemap urlset XML, or a Shopify Admin
        pseudo-source like shopify-admin://all-blogs.
  - Add ?refresh=1 to /feed.xml to force an immediate refresh.
"""

from __future__ import annotations

import argparse
import html
import json
import logging
import os
import random
import threading
import time
from dataclasses import dataclass
from datetime import datetime, timezone, timedelta
from email.utils import format_datetime, parsedate_to_datetime
from logging.handlers import RotatingFileHandler
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any, Iterable
from urllib.parse import parse_qs, unquote, urlencode, urlparse
from urllib.request import Request, urlopen
import xml.etree.ElementTree as ET


DEFAULT_USER_AGENT = "RSSAggregator/1.0 (+https://localhost)"
DEFAULT_CHANNEL_TITLE = "Aggregated RSS Feed"
DEFAULT_CHANNEL_LINK = "http://localhost/"
DEFAULT_CHANNEL_DESCRIPTION = "Merged feed generated by rss_aggregator.py"
DEFAULT_SHOPIFY_API_VERSION = "2026-01"


logger = logging.getLogger("rss_aggregator")


def configure_logging(log_file: str, log_level: str, max_bytes: int, backup_count: int) -> None:
    level_name = (log_level or "INFO").strip().upper()
    level = getattr(logging, level_name, logging.INFO)

    formatter = logging.Formatter(
        fmt="%(asctime)s %(levelname)s [%(name)s] %(message)s",
        datefmt="%Y-%m-%dT%H:%M:%S%z",
    )

    handlers: list[logging.Handler] = []

    stream_handler = logging.StreamHandler()
    stream_handler.setFormatter(formatter)
    handlers.append(stream_handler)

    log_path = (log_file or "").strip()
    if log_path:
        log_dir = os.path.dirname(log_path)
        if log_dir:
            os.makedirs(log_dir, exist_ok=True)
        file_handler = RotatingFileHandler(
            log_path,
            maxBytes=max(1, int(max_bytes)),
            backupCount=max(1, int(backup_count)),
            encoding="utf-8",
        )
        file_handler.setFormatter(formatter)
        handlers.append(file_handler)

    root_logger = logging.getLogger()
    root_logger.handlers.clear()
    root_logger.setLevel(level)
    for handler in handlers:
        root_logger.addHandler(handler)


@dataclass
class FeedItem:
    title: str
    link: str
    description: str
    guid: str
    published: datetime | None
    source_title: str
    source_url: str


def local_name(tag: str) -> str:
    if "}" in tag:
        return tag.split("}", 1)[1].lower()
    return tag.lower()


def parse_iso_datetime(value: str) -> datetime | None:
    text = value.strip()
    if not text:
        return None

    # Handle Zulu timestamps from Atom feeds.
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"

    try:
        dt = datetime.fromisoformat(text)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt
    except ValueError:
        return None


def parse_datetime(value: str) -> datetime | None:
    text = (value or "").strip()
    if not text:
        return None

    try:
        dt = parsedate_to_datetime(text)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc)
    except (TypeError, ValueError):
        pass

    dt = parse_iso_datetime(text)
    if dt is not None:
        return dt.astimezone(timezone.utc)

    # Last fallback for date-only strings.
    for fmt in ("%Y-%m-%d", "%Y/%m/%d"):
        try:
            return datetime.strptime(text, fmt).replace(tzinfo=timezone.utc)
        except ValueError:
            continue
    return None


def child_text(element: ET.Element, names: Iterable[str]) -> str:
    wanted = {n.lower() for n in names}
    for child in element:
        if local_name(child.tag) in wanted:
            text = "".join(child.itertext()).strip()
            if text:
                return text
    return ""


def first_child(element: ET.Element, names: Iterable[str]) -> ET.Element | None:
    wanted = {n.lower() for n in names}
    for child in element:
        if local_name(child.tag) in wanted:
            return child
    return None


def xml_escape(text: str) -> str:
    return html.escape(text or "", quote=True)


def cdata(text: str) -> str:
    # Keep feed markup safe even if content contains CDATA terminator.
    safe = (text or "").replace("]]>", "]]]]><![CDATA[>")
    return f"<![CDATA[{safe}]]>"


def slug_to_title(slug: str) -> str:
    text = unquote((slug or "").strip().strip("/"))
    if not text:
        return "Untitled"
    text = text.replace("-", " ").replace("_", " ")
    text = " ".join(text.split())
    if not text:
        return "Untitled"
    return text.title()


def first_non_empty(*values: str | None) -> str:
    for value in values:
        if value is None:
            continue
        text = str(value).strip()
        if text:
            return text
    return ""


def normalize_shopify_domain(domain: str) -> str:
    text = (domain or "").strip()
    if not text:
        return ""
    return text.replace("https://", "").replace("http://", "").rstrip("/")


class FeedAggregator:
    def __init__(
        self,
        feeds_file: str,
        cache_ttl_seconds: int,
        timeout_seconds: int,
        max_items: int,
        user_agent: str,
        channel_title: str,
        channel_link: str,
        channel_description: str,
        shopify_domain: str,
        shopify_api_version: str,
        shopify_admin_token: str,
        shopify_client_id: str,
        shopify_client_secret: str,
        output_file: str,
    ) -> None:
        self.feeds_file = feeds_file
        self.cache_ttl_seconds = max(0, int(cache_ttl_seconds))
        self.timeout_seconds = max(1, int(timeout_seconds))
        self.max_items = max(1, int(max_items))
        self.user_agent = user_agent.strip() or DEFAULT_USER_AGENT
        self.channel_title = channel_title.strip() or DEFAULT_CHANNEL_TITLE
        self.channel_link = channel_link.strip() or DEFAULT_CHANNEL_LINK
        self.channel_description = channel_description.strip() or DEFAULT_CHANNEL_DESCRIPTION
        self.shopify_domain = normalize_shopify_domain(shopify_domain)
        self.shopify_api_version = first_non_empty(shopify_api_version, DEFAULT_SHOPIFY_API_VERSION)
        self.shopify_admin_token = (shopify_admin_token or "").strip()
        self.shopify_client_id = (shopify_client_id or "").strip()
        self.shopify_client_secret = (shopify_client_secret or "").strip()
        self.output_file = (output_file or "").strip()
        self._shopify_oauth_token = ""
        self._shopify_oauth_expires_at = 0.0

        # Define path for persistent publar state
        self.state_file = ""
        if self.feeds_file:
            base_dir = os.path.dirname(self.feeds_file)
            self.state_file = os.path.join(base_dir, "publar_state.json") if base_dir else "publar_state.json"

        self._lock = threading.Lock()
        self._cached_xml = ""
        self._latest_all_items: list[FeedItem] = []
        self.publar_config: dict[str, Any] = {}
        self._last_refresh_ts = 0.0
        self._last_status: dict[str, object] = {
            "ok": True,
            "refreshed_at": None,
            "feed_count": 0,
            "item_count": 0,
            "errors": [],
        }

    def write_output_file(self, xml_output: str) -> None:
        if not self.output_file:
            return

        output_path = self.output_file
        output_dir = os.path.dirname(output_path)
        if output_dir:
            os.makedirs(output_dir, exist_ok=True)

        tmp_path = f"{output_path}.tmp"
        with open(tmp_path, "w", encoding="utf-8") as fh:
            fh.write(xml_output)
            if not xml_output.endswith("\n"):
                fh.write("\n")
        os.replace(tmp_path, output_path)

    def load_feed_urls(self) -> list[str]:
        urls: list[str] = []
        self.publar_config = {}
        if self.feeds_file.endswith(".json"):
            with open(self.feeds_file, "r", encoding="utf-8") as fh:
                data = json.load(fh)
                if isinstance(data, dict):
                    urls = data.get("feeds", [])
                    self.publar_config = data.get("publar", {})
                elif isinstance(data, list):
                    urls = data
        else:
            with open(self.feeds_file, "r", encoding="utf-8") as fh:
                for raw in fh:
                    line = raw.strip()
                    if not line or line.startswith("#"):
                        continue
                    urls.append(line)
        return urls

    def fetch_feed_text(self, url: str) -> str:
        req = Request(
            url,
            headers={
                "User-Agent": self.user_agent,
                "Accept": "application/rss+xml, application/atom+xml, application/xml, text/xml;q=0.9, */*;q=0.8",
            },
        )
        with urlopen(req, timeout=self.timeout_seconds) as resp:
            raw = resp.read()
            charset = "utf-8"
            content_type = resp.headers.get("Content-Type", "")
            if "charset=" in content_type:
                charset = content_type.split("charset=", 1)[1].split(";", 1)[0].strip() or "utf-8"
        return raw.decode(charset, errors="replace")

    def is_shopify_admin_source(self, source_url: str) -> bool:
        return source_url.strip().lower().startswith("shopify-admin://")

    def _exchange_shopify_oauth_token(self) -> str:
        if not self.shopify_domain:
            raise ValueError("Shopify domain is required for shopify-admin:// sources")
        if not self.shopify_client_id or not self.shopify_client_secret:
            raise ValueError(
                "Shopify client credentials are required. "
                "Set RSS_AGG_SHOPIFY_CLIENT_ID and RSS_AGG_SHOPIFY_CLIENT_SECRET."
            )

        token_url = f"https://{self.shopify_domain}/admin/oauth/access_token"
        payload = urlencode(
            {
                "grant_type": "client_credentials",
                "client_id": self.shopify_client_id,
                "client_secret": self.shopify_client_secret,
            }
        ).encode("utf-8")

        req = Request(
            token_url,
            data=payload,
            method="POST",
            headers={
                "Content-Type": "application/x-www-form-urlencoded",
                "User-Agent": self.user_agent,
            },
        )

        with urlopen(req, timeout=max(self.timeout_seconds, 20)) as resp:
            raw = resp.read().decode("utf-8", errors="replace")

        data = json.loads(raw or "{}")
        token = str(data.get("access_token") or "").strip()
        if not token:
            raise ValueError("Shopify token exchange did not return access_token")

        expires_in = int(data.get("expires_in") or 3600)
        self._shopify_oauth_token = token
        # Refresh 5 minutes early to avoid expiry races.
        self._shopify_oauth_expires_at = time.time() + max(0, expires_in - 300)
        return token

    def _get_shopify_admin_token(self) -> str:
        if self.shopify_admin_token:
            return self.shopify_admin_token
        if self._shopify_oauth_token and time.time() < self._shopify_oauth_expires_at:
            return self._shopify_oauth_token
        return self._exchange_shopify_oauth_token()

    def _shopify_admin_graphql(self, query: str, variables: dict[str, Any] | None = None) -> dict[str, Any]:
        if not self.shopify_domain:
            raise ValueError("Shopify domain is required for shopify-admin:// sources")

        endpoint = f"https://{self.shopify_domain}/admin/api/{self.shopify_api_version}/graphql.json"
        token = self._get_shopify_admin_token()
        payload = json.dumps({"query": query, "variables": variables or {}}).encode("utf-8")
        req = Request(
            endpoint,
            data=payload,
            method="POST",
            headers={
                "Content-Type": "application/json",
                "X-Shopify-Access-Token": token,
                "User-Agent": self.user_agent,
            },
        )

        with urlopen(req, timeout=max(self.timeout_seconds, 30)) as resp:
            raw = resp.read().decode("utf-8", errors="replace")

        data = json.loads(raw or "{}")
        if data.get("errors"):
            err_text = json.dumps(data["errors"], ensure_ascii=False)[:400]
            raise ValueError(f"Shopify Admin GraphQL errors: {err_text}")
        return data.get("data") or {}

    def fetch_shopify_admin_items(self, source_url: str) -> tuple[str, list[FeedItem]]:
        parsed = urlparse(source_url)
        wanted_handle = ""

        if parsed.netloc:
            wanted_handle = parsed.netloc.strip().lower()

        path_token = (parsed.path or "").strip("/").lower()
        if not wanted_handle and path_token:
            wanted_handle = path_token

        query_blog = parse_qs(parsed.query).get("blog", [""])[0].strip().lower()
        if query_blog:
            wanted_handle = query_blog

        if wanted_handle in ("", "all", "all-blogs", "blogs", "all-articles", "articles"):
            wanted_handle = ""

        blogs_query = """
        query AggregatorBlogs($first: Int!, $after: String) {
          blogs(first: $first, after: $after) {
            pageInfo { hasNextPage endCursor }
            edges { node { id title handle } }
          }
        }
        """

        article_query = """
        query AggregatorBlogArticles($id: ID!, $first: Int!, $after: String) {
          blog(id: $id) {
            id
            title
            handle
            articles(first: $first, after: $after) {
              pageInfo { hasNextPage endCursor }
              edges {
                node {
                  id
                  title
                  handle
                  isPublished
                  publishedAt
                  summary
                  body
                  tags
                }
              }
            }
          }
        }
        """

        blogs: list[dict[str, str]] = []
        after: str | None = None
        while True:
            data = self._shopify_admin_graphql(blogs_query, {"first": 50, "after": after})
            blogs_data = data.get("blogs") or {}
            for edge in blogs_data.get("edges") or []:
                node = edge.get("node") or {}
                blog = {
                    "id": str(node.get("id") or "").strip(),
                    "title": str(node.get("title") or "").strip(),
                    "handle": str(node.get("handle") or "").strip(),
                }
                if blog["id"]:
                    blogs.append(blog)

            page = blogs_data.get("pageInfo") or {}
            has_next = bool(page.get("hasNextPage"))
            after = page.get("endCursor") if has_next else None
            if not has_next:
                break

        if wanted_handle:
            blogs = [blog for blog in blogs if blog["handle"].lower() == wanted_handle]

        if not blogs:
            if wanted_handle:
                raise ValueError(f"No Shopify blog found for handle '{wanted_handle}'")
            raise ValueError("No Shopify blogs were returned by Admin API")

        items: list[FeedItem] = []
        for blog in blogs:
            after_cursor: str | None = None
            while True:
                data = self._shopify_admin_graphql(
                    article_query,
                    {
                        "id": blog["id"],
                        "first": 250,
                        "after": after_cursor,
                    },
                )
                blog_data = data.get("blog") or {}
                articles = blog_data.get("articles") or {}

                blog_title = str(blog_data.get("title") or blog["title"] or blog["handle"] or self.shopify_domain)
                blog_handle = str(blog_data.get("handle") or blog["handle"] or "").strip()
                source_page = f"https://{self.shopify_domain}/blogs/{blog_handle}" if blog_handle else f"https://{self.shopify_domain}/blogs"

                for edge in articles.get("edges") or []:
                    node = edge.get("node") or {}
                    # Skip drafts/unpublished entries in public feed output.
                    if node.get("isPublished") is False:
                        continue

                    article_title = str(node.get("title") or "").strip() or "Untitled"
                    article_handle = str(node.get("handle") or "").strip()
                    article_link = (
                        f"https://{self.shopify_domain}/blogs/{blog_handle}/{article_handle}"
                        if blog_handle and article_handle
                        else source_page
                    )
                    guid = str(node.get("id") or "").strip() or article_link or article_title
                    description = str(node.get("summary") or node.get("body") or "")
                    published = parse_datetime(str(node.get("publishedAt") or ""))

                    items.append(
                        FeedItem(
                            title=article_title,
                            link=article_link,
                            description=description,
                            guid=guid,
                            published=published,
                            source_title=blog_title,
                            source_url=source_page,
                        )
                    )

                page = articles.get("pageInfo") or {}
                has_next = bool(page.get("hasNextPage"))
                after_cursor = page.get("endCursor") if has_next else None
                if not has_next:
                    break

        source_title = f"Shopify Admin ({self.shopify_domain})"
        return source_title, items

    def parse_atom_link(self, entry: ET.Element) -> str:
        best = ""
        for child in entry:
            if local_name(child.tag) != "link":
                continue
            href = (child.attrib.get("href") or "").strip()
            rel = (child.attrib.get("rel") or "alternate").strip().lower()
            if not href:
                continue
            if rel in ("alternate", ""):
                return href
            if not best:
                best = href
        return best

    def parse_rss(self, root: ET.Element, source_url: str) -> tuple[str, list[FeedItem]]:
        channel = first_child(root, ["channel"]) or root
        source_title = child_text(channel, ["title"]) or source_url
        items: list[FeedItem] = []

        for node in channel:
            if local_name(node.tag) != "item":
                continue

            title = child_text(node, ["title"]) or "Untitled"
            link = child_text(node, ["link"])
            description = child_text(node, ["description", "encoded", "content"])
            guid = child_text(node, ["guid"]) or link or title
            pub_raw = child_text(node, ["pubDate", "published", "updated", "date"])
            published = parse_datetime(pub_raw)

            items.append(
                FeedItem(
                    title=title,
                    link=link,
                    description=description,
                    guid=guid,
                    published=published,
                    source_title=source_title,
                    source_url=source_url,
                )
            )

        return source_title, items

    def parse_atom(self, root: ET.Element, source_url: str) -> tuple[str, list[FeedItem]]:
        source_title = child_text(root, ["title"]) or source_url
        items: list[FeedItem] = []

        for node in root:
            if local_name(node.tag) != "entry":
                continue

            title = child_text(node, ["title"]) or "Untitled"
            link = self.parse_atom_link(node)
            description = child_text(node, ["summary", "content"])
            guid = child_text(node, ["id"]) or link or title
            pub_raw = child_text(node, ["published", "updated", "issued"])
            published = parse_datetime(pub_raw)

            items.append(
                FeedItem(
                    title=title,
                    link=link,
                    description=description,
                    guid=guid,
                    published=published,
                    source_title=source_title,
                    source_url=source_url,
                )
            )

        return source_title, items

    def parse_sitemap_urlset(self, root: ET.Element, source_url: str) -> tuple[str, list[FeedItem]]:
        source_title = f"Sitemap ({source_url})"
        items: list[FeedItem] = []

        for node in root:
            if local_name(node.tag) != "url":
                continue

            link = child_text(node, ["loc"])
            if not link:
                continue

            parsed = urlparse(link)
            parts = [part for part in parsed.path.split("/") if part]
            # Keep article-level blog URLs and skip blog index pages.
            if len(parts) < 3 or parts[0].lower() != "blogs":
                continue

            title = slug_to_title(parts[-1])
            pub_raw = child_text(node, ["lastmod", "updated", "published", "date"])
            published = parse_datetime(pub_raw)

            items.append(
                FeedItem(
                    title=title,
                    link=link,
                    description="",
                    guid=link,
                    published=published,
                    source_title=source_title,
                    source_url=source_url,
                )
            )

        return source_title, items

    def parse_feed(self, xml_text: str, source_url: str) -> tuple[str, list[FeedItem]]:
        root = ET.fromstring(xml_text)
        name = local_name(root.tag)

        if name in ("rss", "rdf"):
            return self.parse_rss(root, source_url)
        if name == "feed":
            return self.parse_atom(root, source_url)
        if name == "urlset":
            return self.parse_sitemap_urlset(root, source_url)

        # Fall back to RSS style parsing if structure is unusual.
        return self.parse_rss(root, source_url)

    def dedupe_and_sort(self, items: list[FeedItem]) -> list[FeedItem]:
        seen: set[str] = set()
        out: list[FeedItem] = []

        for item in items:
            dedupe_key = (item.guid or item.link or item.title).strip().lower()
            if not dedupe_key:
                dedupe_key = f"{item.title.strip().lower()}::{item.source_url.strip().lower()}"
            if dedupe_key in seen:
                continue
            seen.add(dedupe_key)
            out.append(item)

        self._latest_all_items = out.copy()

        out.sort(
            key=lambda x: x.published or datetime.fromtimestamp(0, tz=timezone.utc),
            reverse=True,
        )
        return out[: self.max_items]

    def build_rss_xml(self, items: list[FeedItem], generated_at: datetime) -> str:
        lines = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<rss version="2.0">',
            "  <channel>",
            f"    <title>{xml_escape(self.channel_title)}</title>",
            f"    <link>{xml_escape(self.channel_link)}</link>",
            f"    <description>{xml_escape(self.channel_description)}</description>",
            f"    <lastBuildDate>{xml_escape(format_datetime(generated_at))}</lastBuildDate>",
            "    <generator>rss_aggregator.py</generator>",
        ]

        for item in items:
            pub = format_datetime(item.published) if item.published else format_datetime(generated_at)
            desc_source = (
                f"<p><strong>Source:</strong> "
                f"<a href=\"{xml_escape(item.source_url)}\">{xml_escape(item.source_title)}</a></p>"
            )
            full_desc = desc_source + (item.description or "")

            lines.extend(
                [
                    "    <item>",
                    f"      <title>{xml_escape(item.title)}</title>",
                    f"      <link>{xml_escape(item.link)}</link>",
                    f"      <guid isPermaLink=\"false\">{xml_escape(item.guid)}</guid>",
                    f"      <pubDate>{xml_escape(pub)}</pubDate>",
                    f"      <description>{cdata(full_desc)}</description>",
                    "    </item>",
                ]
            )

        lines.extend(["  </channel>", "</rss>"])
        return "\n".join(lines)

    def refresh(self) -> tuple[str, dict[str, object]]:
        generated_at = datetime.now(timezone.utc)
        errors: list[str] = []
        all_items: list[FeedItem] = []
        shopify_admin_sources = 0

        try:
            feed_urls = self.load_feed_urls()
        except FileNotFoundError:
            feed_urls = []
            errors.append(f"Feed list file not found: {self.feeds_file}")
        except OSError as exc:
            feed_urls = []
            errors.append(f"Could not read feed list file: {exc}")

        for url in feed_urls:
            try:
                if self.is_shopify_admin_source(url):
                    shopify_admin_sources += 1
                    _source_title, items = self.fetch_shopify_admin_items(url)
                else:
                    xml_text = self.fetch_feed_text(url)
                    _source_title, items = self.parse_feed(xml_text, url)
                all_items.extend(items)
                logger.debug("Fetched source %s with %s items", url, len(items))
            except Exception as exc:  # noqa: BLE001
                err_text = f"{url} -> {exc}"
                errors.append(err_text)
                logger.warning("Source refresh failed: %s", err_text)

        merged_items = self.dedupe_and_sort(all_items)
        xml_output = self.build_rss_xml(merged_items, generated_at)

        try:
            self.write_output_file(xml_output)
        except OSError as exc:
            err_text = f"output_file:{self.output_file} -> {exc}"
            errors.append(err_text)
            logger.warning("Failed to write RSS output file: %s", err_text)

        status: dict[str, object] = {
            "ok": len(errors) == 0,
            "refreshed_at": generated_at.isoformat(),
            "feed_count": len(feed_urls),
            "shopify_admin_sources": shopify_admin_sources,
            "item_count": len(merged_items),
            "errors": errors,
        }
        logger.info(
            "Refresh completed: feeds=%s shopify_admin_sources=%s items=%s errors=%s",
            len(feed_urls),
            shopify_admin_sources,
            len(merged_items),
            len(errors),
        )
        return xml_output, status

    def get_feed_xml(self, force_refresh: bool = False) -> tuple[str, dict[str, object]]:
        with self._lock:
            now = time.time()
            cache_expired = now - self._last_refresh_ts >= self.cache_ttl_seconds

            if force_refresh or not self._cached_xml or cache_expired:
                reason = "force" if force_refresh else "cache_miss_or_expired"
                logger.info("Refreshing feed cache (%s)", reason)
                xml_output, status = self.refresh()
                self._cached_xml = xml_output
                self._last_status = status
                self._last_refresh_ts = now

            return self._cached_xml, self._last_status

    def get_publar_feed_xml(self, force_refresh: bool = False) -> tuple[str, dict[str, object]]:
        with self._lock:
            now_ts = time.time()
            cache_expired = now_ts - self._last_refresh_ts >= self.cache_ttl_seconds

            if force_refresh or not self._cached_xml or cache_expired:
                reason = "force" if force_refresh else "cache_miss_or_expired"
                logger.info("Refreshing feed cache for publar (%s)", reason)
                xml_output, status = self.refresh()
                self._cached_xml = xml_output
                self._last_status = status
                self._last_refresh_ts = now_ts

            # Build the custom publar feed
            publar = self.publar_config or {}
            start_time_str = publar.get("start_time", "2026-06-06T00:00:00Z")
            start_dt = parse_datetime(start_time_str) or datetime.fromtimestamp(0, tz=timezone.utc)
            
            initial_count = int(publar.get("initial_count", 1))
            sort_order = str(publar.get("sort_order", "chronological")).strip().lower()
            
            publar_title = publar.get("channel_title", "Publar Drip Feed")
            publar_desc = publar.get("channel_description", "Drip-released articles randomly between 3-5 hours.")

            pool = list(self._latest_all_items)
            is_reverse = (sort_order == "reverse-chronological")
            pool.sort(
                key=lambda x: x.published or datetime.fromtimestamp(0, tz=timezone.utc),
                reverse=is_reverse,
            )

            # Assign each article a deterministic pseudo-random release time!
            # Seed the PRNG with a stable value so restarts or new requests yield the exact same times.
            # Using the chronological pool items lets the timing sequence remain completely stable
            # even as new articles are appended to the reservoir feed.
            prng = random.Random(42)  # Seed is fixed to 42 for absolute consistency
            
            # chron_pool is chronological (oldest first) so that new articles added over time are appended to the end,
            # ensuring that already assigned intervals of older articles never change!
            chron_pool = list(self._latest_all_items)
            chron_pool.sort(
                key=lambda x: x.published or datetime.fromtimestamp(0, tz=timezone.utc),
                reverse=False,
            )
            
            # Map item to its computed allowed UTC release timestamp
            release_map = {}
            current_release_time = start_dt
            
            for index, item in enumerate(chron_pool):
                if index < initial_count:
                    # Initial items are immediately unlocked at start_time
                    release_map[item.guid or item.link or item.title] = start_dt
                else:
                    # Subsequent items are unlocked after a random 3-5 hours interval
                    random_interval_hours = prng.uniform(3.0, 5.0)
                    current_release_time = current_release_time + timedelta(hours=random_interval_hours)
                    release_map[item.guid or item.link or item.title] = current_release_time

            now_utc = datetime.now(timezone.utc)
            
            # Filter the user-requested pool order based on calculated release times
            visible_items = []
            for item in pool:
                key_id = item.guid or item.link or item.title
                item_release_time = release_map.get(key_id, start_dt)
                if now_utc >= item_release_time:
                    visible_items.append(item)

            allowed_count = len(visible_items)
            elapsed_seconds = max(0.0, (now_utc - start_dt).total_seconds())

            # Persistent State Enforcement:
            # Save the computed allowed count so restarts reads this and knows exactly what number its on.
            if self.state_file:
                loaded_state = {}
                if os.path.exists(self.state_file):
                    try:
                        with open(self.state_file, "r", encoding="utf-8") as sf:
                            loaded_state = json.load(sf)
                    except Exception:
                        pass
                
                # Check if we should increase the count or write it initially
                saved_allowed_count = loaded_state.get("allowed_count", 0)
                
                # If we computed more visible items, update the file state.
                # If the script computes a lower number (due to an absolute clock drift or pool refresh delay),
                # we preserve the higher saved_allowed_count to guarantee we NEVER roll back count on restarts!
                if allowed_count > saved_allowed_count:
                    state_payload = {
                        "allowed_count": allowed_count,
                        "last_updated": now_utc.isoformat(),
                        "start_time": start_time_str
                    }
                    try:
                        with open(self.state_file, "w", encoding="utf-8") as sf:
                            json.dump(state_payload, sf, indent=2)
                    except Exception as exc:
                        logger.warning("Failed to write to state file %s: %s", self.state_file, exc)
                elif saved_allowed_count > allowed_count:
                    # Enforce the persistent fallback limit:
                    allowed_count = saved_allowed_count
                    visible_items = pool[:allowed_count]

            rss_items = sorted(
                visible_items,
                key=lambda x: x.published or datetime.fromtimestamp(0, tz=timezone.utc),
                reverse=True,
            )
            rss_items = rss_items[: self.max_items]

            lines = [
                '<?xml version="1.0" encoding="UTF-8"?>',
                '<rss version="2.0">',
                "  <channel>",
                f"    <title>{xml_escape(publar_title)}</title>",
                f"    <link>{xml_escape(self.channel_link)}</link>",
                f"    <description>{xml_escape(publar_desc)}</description>",
                f"    <lastBuildDate>{xml_escape(format_datetime(now_utc))}</lastBuildDate>",
                "    <generator>rss_aggregator.py</generator>",
            ]

            for item in rss_items:
                pub = format_datetime(item.published) if item.published else format_datetime(now_utc)
                desc_source = (
                    f"<p><strong>Source:</strong> "
                    f"<a href=\"{xml_escape(item.source_url)}\">{xml_escape(item.source_title)}</a></p>"
                )
                full_desc = desc_source + (item.description or "")

                lines.extend(
                    [
                        "    <item>",
                        f"      <title>{xml_escape(item.title)}</title>",
                        f"      <link>{xml_escape(item.link)}</link>",
                        f"      <guid isPermaLink=\"false\">{xml_escape(item.guid)}</guid>",
                        f"      <pubDate>{xml_escape(pub)}</pubDate>",
                        f"      <description>{cdata(full_desc)}</description>",
                        "    </item>",
                    ]
                )

            lines.extend(["  </channel>", "</rss>"])
            publar_xml = "\n".join(lines)

            status = {
                "publar_allowed_count": allowed_count,
                "publar_pooled_count": len(pool),
                "publar_start_time": start_time_str,
                "publar_elapsed_hours": f"{elapsed_seconds / 3600.0:.2f}",
            }
            return publar_xml, status

    def get_health(self) -> dict[str, object]:
        with self._lock:
            auth_mode = "none"
            if self.shopify_admin_token:
                auth_mode = "access_token"
            elif self.shopify_client_id and self.shopify_client_secret:
                auth_mode = "client_credentials"

            publar_stats = {}
            if self.publar_config:
                start_time_str = self.publar_config.get("start_time", "2026-06-06T00:00:00Z")
                start_dt = parse_datetime(start_time_str) or datetime.fromtimestamp(0, tz=timezone.utc)
                initial_count = int(self.publar_config.get("initial_count", 1))
                now_utc = datetime.now(timezone.utc)
                
                # Check how many are currently allowed with the deterministic random schedule
                chron_pool = list(self._latest_all_items)
                chron_pool.sort(
                    key=lambda x: x.published or datetime.fromtimestamp(0, tz=timezone.utc),
                    reverse=False,
                )
                
                prng = random.Random(42)
                allowed_count = 0
                current_release_time = start_dt
                
                for index, item in enumerate(chron_pool):
                    if index < initial_count:
                        item_release_time = start_dt
                    else:
                        random_interval_hours = prng.uniform(3.0, 5.0)
                        current_release_time = current_release_time + timedelta(hours=random_interval_hours)
                        item_release_time = current_release_time
                    
                    if now_utc >= item_release_time:
                        allowed_count += 1
                
                publar_stats = {
                    "publar_enabled": True,
                    "publar_start_time": start_time_str,
                    "publar_initial_count": initial_count,
                    "publar_random_drip": "3.0 to 5.0 hours",
                    "publar_allowed_count": allowed_count,
                    "publar_pooled_count": len(self._latest_all_items),
                }

            return {
                **self._last_status,
                "cache_ttl_seconds": self.cache_ttl_seconds,
                "cache_age_seconds": max(0, int(time.time() - self._last_refresh_ts)) if self._last_refresh_ts else None,
                "feeds_file": self.feeds_file,
                "max_items": self.max_items,
                "shopify_domain": self.shopify_domain or None,
                "shopify_api_version": self.shopify_api_version,
                "shopify_auth_mode": auth_mode,
                "output_file": self.output_file or None,
                "output_file_exists": bool(self.output_file and os.path.exists(self.output_file)),
                **publar_stats,
            }


class AggregatorHTTPServer(ThreadingHTTPServer):
    def __init__(self, server_address: tuple[str, int], handler_cls: type[BaseHTTPRequestHandler], aggregator: FeedAggregator) -> None:
        super().__init__(server_address, handler_cls)
        self.aggregator = aggregator


class FeedRequestHandler(BaseHTTPRequestHandler):
    server: AggregatorHTTPServer

    def _request_full_url(self) -> str:
        forwarded_proto = (self.headers.get("X-Forwarded-Proto") or "").strip()
        scheme = forwarded_proto if forwarded_proto else "http"
        host = (self.headers.get("Host") or "").strip()
        if not host:
            host = self.server.server_name
            port = int(getattr(self.server, "server_port", 0) or 0)
            if port and ((scheme == "http" and port != 80) or (scheme == "https" and port != 443)):
                host = f"{host}:{port}"
        path = self.path or "/"
        return f"{scheme}://{host}{path}"

    def do_HEAD(self) -> None:  # noqa: N802
        parsed = urlparse(self.path)

        if parsed.path in ("/", "/feed", "/feed.xml", "/apps/rss", "/apps/rss/"):
            query = parse_qs(parsed.query)
            refresh_flag = (query.get("refresh", ["0"])[0] or "0").strip().lower()
            force_refresh = refresh_flag in ("1", "true", "yes")

            xml_output, _status = self.server.aggregator.get_feed_xml(force_refresh=force_refresh)
            payload = xml_output.encode("utf-8")

            self.send_response(200)
            self.send_header("Content-Type", "application/rss+xml; charset=utf-8")
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            return

        if parsed.path in ("/publar/rss", "/publar/rss.xml", "/publar/feed", "/publar/feed.xml", "/publar/rss/"):
            query = parse_qs(parsed.query)
            refresh_flag = (query.get("refresh", ["0"])[0] or "0").strip().lower()
            force_refresh = refresh_flag in ("1", "true", "yes")

            xml_output, _status = self.server.aggregator.get_publar_feed_xml(force_refresh=force_refresh)
            payload = xml_output.encode("utf-8")

            self.send_response(200)
            self.send_header("Content-Type", "application/rss+xml; charset=utf-8")
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            return

        if parsed.path == "/health":
            status = self.server.aggregator.get_health()
            payload = json.dumps(status, indent=2).encode("utf-8")

            self.send_response(200)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            return

        payload = b"Not found\n"
        self.send_response(404)
        self.send_header("Content-Type", "text/plain; charset=utf-8")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()

    def do_GET(self) -> None:  # noqa: N802
        parsed = urlparse(self.path)

        if parsed.path in ("/", "/feed", "/feed.xml", "/apps/rss", "/apps/rss/"):
            query = parse_qs(parsed.query)
            refresh_flag = (query.get("refresh", ["0"])[0] or "0").strip().lower()
            force_refresh = refresh_flag in ("1", "true", "yes")

            xml_output, _status = self.server.aggregator.get_feed_xml(force_refresh=force_refresh)
            payload = xml_output.encode("utf-8")

            self.send_response(200)
            self.send_header("Content-Type", "application/rss+xml; charset=utf-8")
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            self.wfile.write(payload)
            return

        if parsed.path in ("/publar/rss", "/publar/rss.xml", "/publar/feed", "/publar/feed.xml", "/publar/rss/"):
            query = parse_qs(parsed.query)
            refresh_flag = (query.get("refresh", ["0"])[0] or "0").strip().lower()
            force_refresh = refresh_flag in ("1", "true", "yes")

            xml_output, _status = self.server.aggregator.get_publar_feed_xml(force_refresh=force_refresh)
            payload = xml_output.encode("utf-8")

            self.send_response(200)
            self.send_header("Content-Type", "application/rss+xml; charset=utf-8")
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            self.wfile.write(payload)
            return

        if parsed.path == "/health":
            status = self.server.aggregator.get_health()
            payload = json.dumps(status, indent=2).encode("utf-8")

            self.send_response(200)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            self.wfile.write(payload)
            return

        payload = b"Not found\n"
        self.send_response(404)
        self.send_header("Content-Type", "text/plain; charset=utf-8")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, fmt: str, *args: object) -> None:
        logger.info(
            "HTTP %s url=%s - %s",
            self.address_string(),
            self._request_full_url(),
            fmt % args,
        )


def parse_args() -> argparse.Namespace:
    default_shopify_domain = normalize_shopify_domain(
        first_non_empty(
            os.getenv("RSS_AGG_SHOPIFY_DOMAIN"),
            os.getenv("MYSHOPIFY_DOMAIN"),
            os.getenv("SHOPIFY_STOREFRONT_DOMAIN"),
        )
    )
    default_shopify_api_version = first_non_empty(
        os.getenv("RSS_AGG_SHOPIFY_API_VERSION"),
        os.getenv("SHOPIFY_API_VERSION"),
        DEFAULT_SHOPIFY_API_VERSION,
    )
    default_shopify_admin_token = first_non_empty(
        os.getenv("RSS_AGG_SHOPIFY_ADMIN_TOKEN"),
        os.getenv("SHOPIFY_ADMIN_ACCESS_TOKEN"),
        os.getenv("SHOPIFY_ACCESS_TOKEN"),
    )
    default_shopify_client_id = first_non_empty(
        os.getenv("RSS_AGG_SHOPIFY_CLIENT_ID"),
        os.getenv("SHOPIFY_CLIENT_ID"),
    )
    default_shopify_client_secret = first_non_empty(
        os.getenv("RSS_AGG_SHOPIFY_CLIENT_SECRET"),
        os.getenv("SHOPIFY_CLIENT_SECRET"),
    )

    parser = argparse.ArgumentParser(description="Aggregate RSS/Atom feeds from a file and serve a merged feed.")
    parser.add_argument("--feeds-file", default=os.getenv("RSS_AGG_FEEDS_FILE", "rss_feeds.json"), help="JSON or text file with feed URLs and publar configuration.")
    parser.add_argument("--host", default=os.getenv("RSS_AGG_HOST", "127.0.0.1"), help="Bind host (default: 127.0.0.1)")
    parser.add_argument("--port", type=int, default=int(os.getenv("RSS_AGG_PORT", "8090")), help="Bind port (default: 8090)")
    parser.add_argument("--cache-ttl", type=int, default=int(os.getenv("RSS_AGG_CACHE_TTL", "300")), help="Cache TTL in seconds (default: 300)")
    parser.add_argument("--timeout", type=int, default=int(os.getenv("RSS_AGG_TIMEOUT", "15")), help="Per-feed fetch timeout in seconds (default: 15)")
    parser.add_argument("--max-items", type=int, default=int(os.getenv("RSS_AGG_MAX_ITEMS", "1000")), help="Max merged items to include (default: 1000)")
    parser.add_argument("--user-agent", default=os.getenv("RSS_AGG_USER_AGENT", DEFAULT_USER_AGENT), help="HTTP User-Agent for feed fetches")
    parser.add_argument("--channel-title", default=os.getenv("RSS_AGG_CHANNEL_TITLE", DEFAULT_CHANNEL_TITLE), help="Channel title for the merged RSS feed")
    parser.add_argument("--channel-link", default=os.getenv("RSS_AGG_CHANNEL_LINK", DEFAULT_CHANNEL_LINK), help="Channel link for the merged RSS feed")
    parser.add_argument("--channel-description", default=os.getenv("RSS_AGG_CHANNEL_DESCRIPTION", DEFAULT_CHANNEL_DESCRIPTION), help="Channel description for the merged RSS feed")
    parser.add_argument("--shopify-domain", default=default_shopify_domain, help="Shopify domain for shopify-admin:// sources")
    parser.add_argument("--shopify-api-version", default=default_shopify_api_version, help="Shopify Admin API version for shopify-admin:// sources")
    parser.add_argument("--shopify-admin-token", default=default_shopify_admin_token, help="Shopify Admin API token (optional when client credentials are set)")
    parser.add_argument("--shopify-client-id", default=default_shopify_client_id, help="Shopify client_id for OAuth client-credentials flow")
    parser.add_argument("--shopify-client-secret", default=default_shopify_client_secret, help="Shopify client_secret for OAuth client-credentials flow")
    parser.add_argument("--output-file", default=os.getenv("RSS_AGG_OUTPUT_FILE", "feed.rss"), help="Write latest merged RSS 2.0 XML to this file on refresh")
    parser.add_argument("--log-file", default=os.getenv("RSS_AGG_LOG_FILE", ""), help="Optional log file path")
    parser.add_argument("--log-level", default=os.getenv("RSS_AGG_LOG_LEVEL", "INFO"), help="Logging level (default: INFO)")
    parser.add_argument("--log-max-bytes", type=int, default=int(os.getenv("RSS_AGG_LOG_MAX_BYTES", "5242880")), help="Max bytes per log file before rotation")
    parser.add_argument("--log-backup-count", type=int, default=int(os.getenv("RSS_AGG_LOG_BACKUP_COUNT", "5")), help="Number of rotated log files to keep")
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    configure_logging(
        log_file=args.log_file,
        log_level=args.log_level,
        max_bytes=args.log_max_bytes,
        backup_count=args.log_backup_count,
    )
    logger.info("Starting RSS aggregator")
    logger.info("Feeds file: %s", args.feeds_file)
    logger.info("RSS output file: %s", args.output_file)
    if args.log_file:
        logger.info("Log file: %s", args.log_file)

    aggregator = FeedAggregator(
        feeds_file=args.feeds_file,
        cache_ttl_seconds=args.cache_ttl,
        timeout_seconds=args.timeout,
        max_items=args.max_items,
        user_agent=args.user_agent,
        channel_title=args.channel_title,
        channel_link=args.channel_link,
        channel_description=args.channel_description,
        shopify_domain=args.shopify_domain,
        shopify_api_version=args.shopify_api_version,
        shopify_admin_token=args.shopify_admin_token,
        shopify_client_id=args.shopify_client_id,
        shopify_client_secret=args.shopify_client_secret,
        output_file=args.output_file,
    )

    # Prime initial cache so /health and /feed have immediate data.
    aggregator.get_feed_xml(force_refresh=True)

    server = AggregatorHTTPServer((args.host, args.port), FeedRequestHandler, aggregator)
    logger.info("Serving aggregated feed on http://%s:%s/feed.xml", args.host, args.port)
    logger.info("Health endpoint: http://%s:%s/health", args.host, args.port)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        logger.info("Shutting down...")
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
